import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/Providers";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Ejik News and Stories",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={outfit.className}>
				<ReactQueryProvider>
					<Navbar />
					{children}
					<Footer />
				</ReactQueryProvider>
			</body>
		</html>
	);
}
